Page({
  data:{
    dinosaur:[
      {
        dname:"霸王龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/lexus.jpg"
      },
      {
        dname:"迅猛龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/velociraptor.jpg"
      },
      {
        dname:"翼龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/pterosaur.jpg"
      },
      {
        dname:"腕龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/brachiosaurus.jpg"
      },
      {
        dname:"甲龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/ankylosaur.jpg"
      },
      {
        dname:"剑龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/jianlong.png"
      },
      {
        dname:"黑瑞龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/heiruilong.png"
      },
      {
        dname:"副栉龙",
        imgsrc:"/pages/index/dinosaur/dinosaur/fuzhilong.png"
      },
    ]
  }
})